# This is a basic workflow to help you get started with Actions

name: azure bicep delete

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}
          
      - name: Azure bicep delete
        working-directory: '${{github.workspace}}/'
        run: |
            az resource delete --ids "/subscriptions/c385d199-ccad-473f-a6f5-7fb2c26e7bcc/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/storers42dtv6kcrsc"

      - name: verify Deletion 
        run: |
            az resource show --ids "/subscriptions/c385d199-ccad-473f-a6f5-7fb2c26e7bcc/resourceGroups/rg1/providers/Microsoft.Storage/storageAccounts/storers42dtv6kcrsc" || echo "Resource not found (deleted)"
